apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: pacman-kikd
      namespace: pacman
    patch: |-
      - op: replace 
        path: /spec/replicas 
        value: 3
      - op: add 
        path: /metadata/labels/testkey 
        value: testvalue