apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=quay.io/fabricio211/test
    argocd-image-updater.argoproj.io/write-back-method: git:secret:default/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fabriciolfj/gitops.git
    path: ch07/bgdui/bgdk
    targetRevision: main
  syncPolicy:
    automated: {}