apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries: 
    - name: RedHat Quay 
      api_url: https://quay.io 
      prefix: quay.io 
      insecure: yes
      credentials: pullsecret:argocd/quayio