image:
  repository: quay.io/gitops-cookbook/music
  tag: "1.0.0"
  pullPolicy: Always
  containerPort: 8080

replicaCount: 1

postgresql:
  server: jdbc:postgresql://music-db-postgresql:5432/postgres
  postgresqlUsername: postgres
  secretName: music-db-postgresql
  secretKey: postgres-password